enum ActionTypes{
    GET_SUPERHEROES = "GET_SUPERHEROES",
    GET_SUPERHERO = "GET_SUPERHERO",
    CREATE_SUPERHERO = "CREATE_SUPERHERO",
    EDIT_SUPERHERO = "EDIT_SUPERHERO",
    DELETE_SUPERHERO = "DELETE_SUPERHERO"
}

export default ActionTypes